### ISSUE TITLE
new clearTimeout fix breaks tests 

### ISSUE THREAD

**Issue by clubajax** [cjohansen/sinon-web#33]
This code:
if (typeof timerId === 'object') {
      timerId = timerId.id;
}
...is not accounting for null. Suggest:
if (timerId && typeof timerId === 'object') {
      timerId = timerId.id;
}

**Comment by cjohansen** [comment]
In what situations will it be null? Has this caused an actual problem on your end?

**Comment by clubajax** [comment]
The bug is more for Sinon (and I think they've already fixed it), not Sinon-web. I put the ticket here by mistake, so I'm not sure if it applies or not. The null happens in NodeJS, but I don't have the stack trace handy at the moment for the exact situation.

**Comment by larsthorup** [comment]
I have this same issue when trying to write a test that involves Bootstrap carousel. Apparently the carousel code will invoke clearInterval(null), which causes sinon to fail with this error. Ordinary browsers appear to allow this. Would it make sense to have sinon accept this usage too?

**Comment by cjohansen** [comment]
It would. PR welcome!

**Comment by larsthorup** [comment]
PR created: https://github.com/cjohansen/Sinon.JS/pull/497
