### ISSUE TITLE
Document `spy.printf`?

### ISSUE THREAD

**Issue by domenic** [cjohansen/sinon-web#9]
I'd like to take a dependency on `spy.printf`, for purposes of <a href="https://github.com/domenic/sinon-chai/issues/4#issuecomment-4291431">getting better error messages in sinon-chai</a>.

However, it's currently undocumented and used in the internals, so I'd feel a bit queasy using it, since it could theoretically disappear at any moment to be replaced with another mechanism.

Are you open to documenting it, and thus guaranteeing it will stick around in a backward-compatible form? If so I'd be happy to spend some time putting together a pull request.

**Comment by cjohansen** [comment]
Sure, printf is here to stay, feel free to put it in the docs.
